#!/usr/bin/env ruby

name = ARGV[0].to_s.gsub(/[^a-zA-Z0-9]/, '-')

script  = "tell application \"Übersicht\" to refresh"
script += " widget id \"#{name}\"" unless name.empty?

exec("osascript -e '#{script}'")
